const actions = {
  ACTIVE_HEADER_LINK: 'ACTIVE_HEADER_LINK',
  BROWSER_HISTORY: 'BROWSER_HISTORY',
  FORM_CHANGE: 'FORM_CHANGE',
  FORM_SUBMIT: 'FORM_SUBMIT',
  POLLING_RESULTS: 'POLLING_RESULTS',
  SEND_RESULTS: 'SEND_RESULTS',
  SOCKET_IO_CONNECT: 'SOCKET_IO_CONNECT',
  SOCKET_IO_RECIEVE: 'SOCKET_IO_RECIEVE',
  SOCKET_IO_SEND: 'SOCKET_IO_SEND'
}

export default actions
